
bufoon:
  storage:
    db: #数据库设置
      master:
        username: root
        password: root
        filters: mergeStat,wall,logback
        initialSize: 5
        maxActive: 50
        minIdle: 5
        maxWait: 6000
        validationQuery: SELECT 1
        testOnBorrow: true
        testOnReturn: true
        testWhileIdle: true
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        removeAbandoned: true
        removeAbandonedTimeout: 1800
        logAbandoned: true
        url: jdbc:mysql://127.0.0.1:3306/bufoon_framework_demo_master?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&useSSL=false
      slavess:
        username: root
        password: root
        filters: mergeStat,wall,logback
        initialSize: 5
        maxActive: 50
        minIdle: 5
        maxWait: 6000
        validationQuery: SELECT 1
        testOnBorrow: true
        testOnReturn: true
        testWhileIdle: true
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        removeAbandoned: true
        removeAbandonedTimeout: 1800
        logAbandoned: true
        url: jdbc:mysql://127.0.0.1:3306/bufoon_framework_demo_slave?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&useSSL=false
      mybatis-plus:
        mapper-locations: classpath:/config/mappers/*Mapper.xml
        #实体扫描，多个package用逗号或者分号分隔
        typeAliasesPackage: com.bufoon.demo.entity
        #typeEnumsPackage: com.bufoon.demo.entity.enums
        global-config:
          #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
          id-type: 2
          #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
          field-strategy: 2
          #驼峰下划线转换
          db-column-underline: true
          #刷新mapper 调试神器
          refresh-mapper: true
          #数据库大写下划线转换
          #capital-mode: true
          #逻辑删除配置（下面3个配置）
          logic-delete-value: 0
          logic-not-delete-value: 1
          #自定义SQL注入器
          #sql-injector: com.baomidou.springboot.xxx
          # SQL 解析缓存，开启后多租户 @SqlParser 注解生效
          #sql-parser-cache: true
        configuration:
          map-underscore-to-camel-case: true
          cache-enabled: false
server:
  port: 8081
logging:
  level:
    com.bufoon: debug
